# Generated by Django 5.0 on 2023-12-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('todos', '0003_alter_todo_options_alter_todo_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='cliente',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cpf cliente'),
            preserve_default=False,
        ),
    ]
