# Generated by Django 5.0 on 2023-12-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
        ('todos', '0004_todo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livro.livro', verbose_name='Livro'),
            preserve_default=False,
        ),
    ]
