# Generated by Django 5.0 on 2023-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.DateField(null=True, verbose_name='Entregue em'),
        ),
    ]
