# Generated by Django 5.0 on 2023-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_deadline_alter_todo_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Notificado'),
        ),
    ]
